### PR TITLE
Adhit rider dashboard

### PR DESCRIPTION
**Pull request by adhit-s**
https://ucsb-cs156-m23.github.io/proj-gauchoride-m23-9am-1/prs/31/storybook/?path=/story/pages-riderpage--default
Screenshot 2023-08-20 at 7 11 17 PM
Screenshot 2023-08-20 at 7 11 41 PM

### CODE REVIEW

**Review by pabucsb — COMMENTED** [review]
Looks good to me. My only suggestion would be to make the dashboard page only display the current riders rides

**Review by pconrad — CHANGES_REQUESTED** [review]
For links in the PR description, it makes no sense to use localhost links.  Those only work on your computer, and only when you are running the appropriate server.

For storybook links, every PR automatically has a storybook deployment here. Use the link appropriate to your PR, and link directly to the appropriate story or stories.

https://ucsb-cs156-m23.github.io/proj-gauchoride-m23-9am-1/

For pages in the running app, make a dokku deployment and link to that.

**Review by pabucsb — DISMISSED** [review]
LGTM

**Comment by adhit-s** [comment]
Sorry about the huge PR... I misinterpreted the task initially and there was a lot of legacy backend stuff to fix

**Comment by pconrad** [comment]
Tests still not passing, so closing this PR without merging

**Pull request closed without merging**
